// export interface IProductos{
//     codigo?: string;
//     id:string;
//     nombre:string;
//     descripcion:string;
//     precio:number;
//     img:string;
// }

// // Generated by https://quicktype.io

export interface IProductos {
    codigo?:string;
    id:               number;
    Nombre:           string;
    Precio:           number;
    CPU:              string;
    GPU:              string;
    RAM:              number;
    TipoRam:          String;
    PSU:              string;
    ENFRIAMIENTO:     string;
    Almacenamiento:   string;
    cat:              string;
    img:              string;
    Almacenamiento2?: string;
}

// export enum TipoRAM {
//     Ddr5 = "DDR5",
//     Drr4 = "DRR4",
// }

// export enum Cat {
//     AMD = "AMD",
//     Intel = "Intel",
// }
